<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function custom_voting_menu(){
  $items['admin/config/user-interface/vote'] = array(
    'title' => 'Voting',
    'description' => 'Custom voting for all nodes',  
    'page callback' => 'custom_voting_save_config',
    'access arguments' => array('administer shortcuts'),    
  );
  
  $items['admin/config/user-interface/vote/settings'] = array(
    'title' => 'Voting',
    'description' => 'Custom voting for all nodes',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_voting_settings'),
    'access arguments' => array('administer shortcuts'),
    'file' => 'custom_voting.admin.inc',
  );
  
  return $items;
}

function custom_voting_block_info(){
  $block['vote_button'] = array(
    'info' => 'Vote Button',
    'description' => 'Vote for this node',
    'cache' => DRUPAL_NO_CACHE,
  );
  
  return $block;
}

function custom_voting_block_view($delta = ''){
  if($delta == 'vote_button') {
    $block['subject'] = 'Voting Button';
    $block['content'] = func_voting_implementation();   
    return $block;
  }  
}

function func_voting_implementation(){ 
  $node = menu_get_object(); 
  if($node->type == 'article'){  
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'submit',
    );
    $x = "I am Prashant Gaurav";
    return theme('custom-voting',array('form'=>$form)); 
  }
}
 
function custom_voting_theme() {     
  return array(
    'custom-voting' => array(
      'template' => 'custom-voting', 
      'variables'=> array(
        'form'=>NULL,
      ),
    ),   
  ); 
}
