<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function plusone_menu() {
  $items['drupal-js'] = array(
    'title' => 'Plus one',
    'description' => 'plus one',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plusone_form'),
    'access callback' => TRUE,
  );

  return $items;
}

function plusone_form($form, &$form_state) { 
  drupal_add_js('foobar.js');

  $form['foobar_A_check'] = array(
    '#type' => 'checkbox',
    '#prefix' => '',
  );
  $form['foobar_A_text'] = array(
    '#type' => 'textfield',
    '#suffix' => ''
  );
  return $form;
}
